### PR TITLE
amended the tutorials link to the sails 101 github page

### PR DESCRIPTION
**Pull request by chrisjbatts**
previous link no longer working.

### CODE REVIEW

**Comment by loicsaintroch** [comment]
Thank you @chrisjbatts

**Comment by skozz** [comment]
This continues happening in the latest version of Sails. Currently http://links.sailsjs.org/community/sails101 (404)

**Comment by chrisjbatts** [comment]
odd. @skozz maybe no further version has been released yet?

**Comment by skozz** [comment]
@chrisjbatts You are right, the latest version of Sails is '15 days ago' and this issue '9 days ago'. Sorry, my fault.

**Comment by chrisjbatts** [comment]
No problem :) good luck with it all

**Pull request merged**
